services:
  dnas-test:
    build: 
      context: .
      args:
        jakxip: "your_server_ip_here"
        dnasip: "your_dnas_ip_here"
    ports:
      - "443:443"
      - "53:53/udp"
      - "53:53/tcp"
    restart: 'always'
